#  -- NekoInbox Worker 配置 --
#  此文件用于配置驱动后端的 Cloudflare Worker。
#  更多详情请参阅 Wrangler 官方文档: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "nekoinbox-worker" #  你可以在这里重命名你的 Worker。
main = "worker.js"
compatibility_date = "2025-08-02"

# --- KV 命名空间绑定 ---
#  将你的 Worker 与用于数据存储的 Cloudflare KV 命名空间相关联。
#  1. 在 Cloudflare 仪表盘或通过命令行创建一个 KV 命名空间：
#     `wrangler kv:namespace create "FEEDBACK_KV"`
#  2. Wrangler 会在此文件中自动生成一个 `preview_id`。
#  3. 将第 1 步命令输出的生产环境 `id` 粘贴到下方。
[[kv_namespaces]]
binding = "FEEDBACK_KV"
id = "YOUR_KV_NAMESPACE_ID_HERE" #  <-- 重要：请替换为你的 KV 命名空间 ID。
# preview_id = "..." #  (运行 `wrangler dev` 时会自动生成)

# --- 环境变量与密钥 ---
#  这些变量用于配置 Worker 的行为。
#  公开安全的变量可以直接定义在 [vars] 中。
#  敏感信息(密钥)必须使用 `wrangler secret put` 命令进行设置。

[vars]
#  这是 Cloudflare Turnstile (人机验证) 的公钥 (Site Key)。
#  你可以从 Cloudflare 仪表盘的 Turnstile 站点设置中获取。
TURNSTILE_SITE_KEY = "YOUR_TURNSTILE_SITE_KEY_HERE" #  <-- 重要：请替换为你的站点公钥。

# --- 密钥 (Secrets) ---
#  以下值为敏感信息，必须通过命令行设置。
#  请勿将它们直接写入此文件。
#
#  在你的终端中运行以下命令：
#
#  wrangler secret put TURNSTILE_SECRET_KEY
#  (根据提示粘贴你的 Turnstile Secret Key)
#
#  wrangler secret put ADMIN_PASSWORD
#  (输入一个健壮的管理员登录密码)
#
#  wrangler secret put JWT_SECRET
#  (输入一个长而随机的字符串，用于签发登录凭证)
#
#  wrangler secret put API_TOKEN
#  (输入一个长而随机的字符串，供 NoneBot 插件使用)
#
#  # 可选：用于接收举报邮件提醒
#  wrangler secret put RESEND_API_KEY
#  wrangler secret put SENDER_EMAIL
#  wrangler secret put RECIPIENT_EMAIL